Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
var randomDiceRollPair = ObjectPair.PickRandom(diceRolls);
var randomCardPair = ObjectPair.PickRandom(cards);

Console.WriteLine("Random Dice Roll Pair:");
Console.WriteLine($"{((DiceRoll)randomDiceRollPair.Item1).Value}");
Console.WriteLine($"{((DiceRoll)randomDiceRollPair.Item2).Value}");

Console.WriteLine("Random Card Pair:");
Console.WriteLine($"{((Card)randomCardPair.Item1).Rank} of {((Card)randomCardPair.Item1).Suit}");
Console.WriteLine($"{((Card)randomCardPair.Item2).Rank} of {((Card)randomCardPair.Item2).Suit}");
------------------

----- stderr -----

(1,48): error CS0103: The name 'diceRolls' does not exist in the current context

(2,44): error CS0103: The name 'cards' does not exist in the current context
------------------



