Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class MyEventPublisher
{
    public delegate void MyEventHandler (object sender, MyEventArgs e);

    public event MyEventHandler MyEvent;

    public void RaiseEvent()
        => MyEvent?.Invoke(this, new MyEventArgs(this, "Event triggered!"));
}
------------------

----- stderr -----

(8,50): error CS1503: Argument 1: cannot convert from 'MyEventPublisher [ℛ*c3479353-7303-49a6-b28a-e499db54e1cc#1-8, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]' to 'MyEventPublisher [ℛ*c3479353-7303-49a6-b28a-e499db54e1cc#1-3, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]'
------------------



